// ============================================================================
// model3d.js — Catálogo local de modelos 3D.
//
// Cada vehículo de la base de datos apunta (vía MODEL3D_MAP) a un "stage"
// (MODEL3D_STAGES). Cada stage es un único archivo .glb bundlEado en el
// proyecto en /assets/3d/cars/<stage>.glb.
//
// Regla de reuso: varios anuncios del MISMO modelo base comparten stage.
// Cuando no existe un modelo exacto se usa el equivalente visual más cercano
// (misma silueta / tipo de carrocería / marca) y se marca en MODEL3D_FALLBACK.
//
// Todo el contenido es LOCAL. No se realiza ninguna descarga en runtime.
// ============================================================================

const MODEL3D_STAGES = {
  // --- Superdeportivos / deportivos -------------------------------------------------
  "lambo-huracan": "/assets/3d/cars/lambo-huracan.glb",
  "lambo-aventador": "/assets/3d/cars/lambo-aventador.glb",
  "lambo-revuelto": "/assets/3d/cars/lambo-revuelto.glb",
  "lambo-urus": "/assets/3d/cars/lambo-urus.glb",
  "ferrari-f812": "/assets/3d/cars/ferrari-f812.glb",
  "ferrari-sf90": "/assets/3d/cars/ferrari-sf90.glb",
  "ferrari-roma": "/assets/3d/cars/ferrari-roma.glb",
  "ferrari-f488": "/assets/3d/cars/ferrari-f488.glb",
  "mclaren-artura": "/assets/3d/cars/mclaren-artura.glb",
  "mclaren-720s": "/assets/3d/cars/mclaren-720s.glb",
  "mclaren-570s": "/assets/3d/cars/mclaren-570s.glb",
  "porsche-911": "/assets/3d/cars/porsche-911.glb",
  "porsche-cayman": "/assets/3d/cars/porsche-cayman.glb",
  "porsche-taycan": "/assets/3d/cars/porsche-taycan.glb",
  "porsche-panamera": "/assets/3d/cars/porsche-panamera.glb",
  "bmw-m3-sedan": "/assets/3d/cars/bmw-m3-sedan.glb",
  "bmw-m4": "/assets/3d/cars/bmw-m4.glb",
  "bmw-m5": "/assets/3d/cars/bmw-m5.glb",
  "bmw-i8": "/assets/3d/cars/bmw-i8.glb",
  "audi-r8": "/assets/3d/cars/audi-r8.glb",
  "audi-rs7": "/assets/3d/cars/audi-rs7.glb",
  "audi-q7": "/assets/3d/cars/audi-q7.glb",
  "toyota-supra": "/assets/3d/cars/toyota-supra.glb",
  "toyota-land-cruiser": "/assets/3d/cars/toyota-land-cruiser.glb",
  "nissan-gtr": "/assets/3d/cars/nissan-gtr.glb",
  "nissan-370z": "/assets/3d/cars/nissan-370z.glb",
  "maserati-gt": "/assets/3d/cars/maserati-gt.glb",
  "mercedes-amg-gt": "/assets/3d/cars/mercedes-amg-gt.glb",
  "chevrolet-camaro": "/assets/3d/cars/chevrolet-camaro.glb",
  "chevrolet-corvette-c8": "/assets/3d/cars/chevrolet-corvette-c8.glb",
  "dodge-challenger": "/assets/3d/cars/dodge-challenger.glb",
  "ford-mustang": "/assets/3d/cars/ford-mustang.glb",
  "ford-f150-raptor": "/assets/3d/cars/ford-f150-raptor.glb",
  "honda-civic-typer": "/assets/3d/cars/honda-civic-typer.glb",
  "honda-nsx": "/assets/3d/cars/honda-nsx.glb",
  "hyundai-veloster": "/assets/3d/cars/hyundai-veloster.glb",
  "hyundai-tucson": "/assets/3d/cars/hyundai-tucson.glb",
  "hyundai-creta": "/assets/3d/cars/hyundai-creta.glb",
  "hyundai-sonata": "/assets/3d/cars/hyundai-sonata.glb",
  "hyundai-elantra-n": "/assets/3d/cars/hyundai-elantra-n.glb",
  "subaru-wrx": "/assets/3d/cars/subaru-wrx.glb",
  "mazda-rx7": "/assets/3d/cars/mazda-rx7.glb",
  "volkswagen-golf": "/assets/3d/cars/volkswagen-golf.glb",
  "tesla-cybertruck": "/assets/3d/cars/tesla-cybertruck.glb",
  "aston-martin-vantage": "/assets/3d/cars/aston-martin-vantage.glb",
  "offroad-truck": "/assets/3d/cars/offroad-truck.glb",
};

// vehicle id -> stage. Un anuncio puede reusar el stage de otro si comparte
// el modelo base o una silueta equivalente (ver MODEL3D_FALLBACK).
const MODEL3D_MAP = {
  "aston-martin-db12": "aston-martin-vantage",
  "aston-martin-vantage": "aston-martin-vantage",
  "bmw-m4-competition": "bmw-m4",
  "chevrolet-corvette-z06": "chevrolet-corvette-c8",
  "hyundai-i30n": "hyundai-veloster",
  "jeep-wrangler-rubicon": "toyota-land-cruiser",
  "kia-ev6-gt": "hyundai-tucson",
  "kia-stinger-gt": "audi-rs7",
  "lamborghini-huracan-evo": "lambo-huracan",
  "mercedes-s63-amg": "mercedes-amg-gt",
  "nissan-z-nismo": "nissan-370z",
  "suzuki-swift-sport": "volkswagen-golf",
  "tesla-model-s-plaid": "porsche-taycan",
  "audi-etron-gt": "porsche-taycan",
  "audi-r8-v10": "audi-r8",
  "audi-rs6-avant": "porsche-panamera",
  "audi-rs7-sportback": "audi-rs7",
  "audi-sq8": "audi-q7",
  "bentley-bentayga": "audi-q7",
  "bentley-continental-gt": "maserati-gt",
  "bmw-i7": "bmw-m3-sedan",
  "bmw-i8": "bmw-i8",
  "bmw-m5-cs": "bmw-m5",
  "bmw-x5m-competition": "lambo-urus",
  "byd-han-ev": "hyundai-sonata",
  "byd-seal": "hyundai-elantra-n",
  "chevrolet-camaro-zl1": "chevrolet-camaro",
  "chevrolet-silverado-zr2": "ford-f150-raptor",
  "chevrolet-tahoe-rst": "toyota-land-cruiser",
  "dodge-demon-170": "dodge-challenger",
  "dodge-charger-hellcat": "dodge-challenger",
  "ferrari-296-gtb": "ferrari-f488",
  "ferrari-812-competizione": "ferrari-f812",
  "ferrari-roma": "ferrari-roma",
  "ferrari-sf90-stradale": "ferrari-sf90",
  "ford-bronco-raptor": "ford-f150-raptor",
  "ford-f150-raptor-r": "ford-f150-raptor",
  "ford-gt": "mclaren-570s",
  "ford-mustang-gt": "ford-mustang",
  "honda-accord": "hyundai-sonata",
  "honda-civic-type-r": "honda-civic-typer",
  "honda-integra-types": "subaru-wrx",
  "honda-nsx-types": "honda-nsx",
  "hyundai-ioniq5n": "hyundai-tucson",
  "jeep-grand-cherokee-trackhawk": "lambo-urus",
  "lamborghini-aventador-svj": "lambo-aventador",
  "lamborghini-revuelto": "lambo-revuelto",
  "lamborghini-urus-performante": "lambo-urus",
  "lexus-lc500": "maserati-gt",
  "lexus-rx-fsport": "hyundai-tucson",
  "mazda-cx5": "hyundai-tucson",
  "mazda-mx5-miata": "mazda-rx7",
  "mclaren-750s": "mclaren-720s",
  "mclaren-artura": "mclaren-artura",
  "mercedes-amg-gle63": "lambo-urus",
  "mercedes-amg-gt-63": "mercedes-amg-gt",
  "mercedes-c63-amg": "bmw-m3-sedan",
  "mercedes-g63-amg": "toyota-land-cruiser",
  "nissan-ariya": "hyundai-creta",
  "nissan-frontier": "offroad-truck",
  "nissan-gtr-nismo": "nissan-gtr",
  "peugeot-308-gt": "volkswagen-golf",
  "peugeot-508-peugeot-sport": "subaru-wrx",
  "porsche-718-cayman-gt4": "porsche-cayman",
  "porsche-911-carrera": "porsche-911",
  "porsche-cayenne-turbogt": "audi-q7",
  "porsche-taycan-turbos": "porsche-taycan",
  "renault-arkana": "hyundai-creta",
  "renault-megane-rs": "honda-civic-typer",
  "rivian-r1s": "audi-q7",
  "rivian-r1t": "offroad-truck",
  "rolls-royce-cullinan": "audi-q7",
  "rolls-royce-ghost": "mercedes-amg-gt",
  "subaru-outback": "hyundai-creta",
  "subaru-wrx-sti": "subaru-wrx",
  "suzuki-jimny": "toyota-land-cruiser",
  "tesla-cybertruck": "tesla-cybertruck",
  "tesla-model-3-performance": "porsche-taycan",
  "tesla-model-x-plaid": "audi-q7",
  "toyota-camry-trd": "hyundai-sonata",
  "toyota-gr-corolla": "honda-civic-typer",
  "toyota-gr-supra": "toyota-supra",
  "toyota-land-cruiser": "toyota-land-cruiser",
  "volkswagen-golf-r": "volkswagen-golf",
  "volkswagen-id4": "hyundai-tucson",
  "volkswagen-touareg": "audi-q7",
  "volvo-xc60": "hyundai-tucson",
  "volvo-xc90-recharge": "audi-q7",
};

// Vehículos cuyo stage es un modelo aproximado (no el coche exacto).
// Clave: id de vehículo -> descripción del modelo real vs. el stage usado.
const MODEL3D_FALLBACK = {
  "aston-martin-db12": "DB12 (coupé) -> Aston Martin Vantage Roadster (misma familia/marca)",
  "hyundai-i30n": "i30 N -> Hyundai Veloster N (hot hatch Hyundai N)",
  "jeep-wrangler-rubicon": "Wrangler Rubicon -> Toyota Land Cruiser 300 (4x4 todoterreno)",
  "kia-ev6-gt": "EV6 GT -> Hyundai Tucson (crossover compacto)",
  "kia-stinger-gt": "Stinger GT -> Audi RS7 Sportback (berlina fastback)",
  "mercedes-s63-amg": "S63 AMG -> Mercedes-AMG GT (Mercedes premium)",
  "nissan-z-nismo": "Z Nismo -> Nissan 370Z (coupé deportivo Z)",
  "suzuki-swift-sport": "Swift Sport -> VW Golf (compacto/hot hatch)",
  "tesla-model-s-plaid": "Model S -> Porsche Taycan (berlina eléctrica)",
  "audi-etron-gt": "e-tron GT -> Porsche Taycan (misma plataforma eléctrica)",
  "audi-rs6-avant": "RS6 Avant (familiar) -> Porsche Panamera Sport Turismo (shooting brake)",
  "bentley-bentayga": "Bentayga -> Audi Q7 (SUV de lujo de gran tamaño)",
  "bentley-continental-gt": "Continental GT -> Maserati GranTurismo (gran turismo de lujo)",
  "bmw-i7": "i7 -> BMW M3 Sedan (BMW berlina)",
  "bmw-x5m-competition": "X5 M -> Lamborghini Urus (SUV de altas prestaciones)",
  "byd-han-ev": "Han EV -> Hyundai Sonata (berlina)",
  "byd-seal": "Seal -> Hyundai Elantra N (berlina deportiva)",
  "chevrolet-silverado-zr2": "Silverado ZR2 -> Ford F-150 Raptor (pickup off-road)",
  "chevrolet-tahoe-rst": "Tahoe RST -> Toyota Land Cruiser (SUV de gran tamaño)",
  "dodge-charger-hellcat": "Charger Hellcat (sedán) -> Dodge Challenger Hellcat (misma familia Hellcat)",
  "ferrari-296-gtb": "296 GTB -> Ferrari F488 (superdeportivo motor central V8)",
  "ford-bronco-raptor": "Bronco Raptor -> Ford F-150 Raptor (misma familia Raptor off-road)",
  "ford-gt": "Ford GT -> McLaren 570S (superdeportivo motor central)",
  "honda-accord": "Accord -> Hyundai Sonata (berlina media)",
  "honda-integra-types": "Integra Type S -> Subaru WRX (berlina deportiva compacta)",
  "hyundai-ioniq5n": "Ioniq 5 N -> Hyundai Tucson (SUV/crossover compacto)",
  "jeep-grand-cherokee-trackhawk": "Grand Cherokee Trackhawk -> Lamborghini Urus (SUV de altas prestaciones)",
  "lexus-lc500": "LC 500 -> Maserati GranTurismo (gran turismo coupé de lujo)",
  "lexus-rx-fsport": "RX F Sport -> Hyundai Tucson (crossover SUV)",
  "mazda-cx5": "CX-5 -> Hyundai Tucson (crossover SUV)",
  "mazda-mx5-miata": "MX-5 Miata -> Mazda RX-7 (deportivo Mazda)",
  "mercedes-amg-gle63": "AMG GLE 63 S -> Lamborghini Urus (SUV de altas prestaciones)",
  "mercedes-amg-gt-63": "AMG GT 63 4-Door -> Mercedes-AMG GT (marca/plataforma AMG GT)",
  "mercedes-c63-amg": "C63 AMG -> BMW M3 Sedan (berlina deportiva compacta)",
  "mercedes-g63-amg": "G63 AMG -> Toyota Land Cruiser (SUV cuadrado todoterreno)",
  "nissan-ariya": "Ariya -> Hyundai Creta (crossover compacto)",
  "nissan-frontier": "Frontier -> Ford Avalanche A1 (pickup)",
  "peugeot-308-gt": "308 GT -> VW Golf (hot hatch europeo)",
  "peugeot-508-peugeot-sport": "508 PSE -> Subaru WRX (berlina)",
  "porsche-cayenne-turbogt": "Cayenne Turbo GT -> Audi Q7 (misma plataforma VW/Audi)",
  "renault-arkana": "Arkana -> Hyundai Creta (crossover compacto)",
  "renault-megane-rs": "Mégane R.S. -> Honda Civic Type R (hot hatch)",
  "rivian-r1s": "R1S -> Audi Q7 (SUV eléctrico de gran tamaño)",
  "rivian-r1t": "R1T -> Ford Avalanche A1 (pickup eléctrica)",
  "rolls-royce-cullinan": "Cullinan -> Audi Q7 (SUV de lujo)",
  "rolls-royce-ghost": "Ghost -> Mercedes-AMG GT (premium)",
  "subaru-outback": "Outback -> Hyundai Creta (crossover/familiar SUV)",
  "suzuki-jimny": "Jimny -> Toyota Land Cruiser (4x4 cuadrado)",
  "tesla-model-3-performance": "Model 3 -> Porsche Taycan (berlina eléctrica)",
  "tesla-model-x-plaid": "Model X -> Audi Q7 (SUV eléctrico de gran tamaño)",
  "toyota-camry-trd": "Camry TRD -> Hyundai Sonata (berlina media)",
  "toyota-gr-corolla": "GR Corolla -> Honda Civic Type R (hot hatch)",
  "volkswagen-id4": "ID.4 -> Hyundai Tucson (crossover eléctrico)",
  "volkswagen-touareg": "Touareg R -> Audi Q7 (misma plataforma VW/Audi)",
  "volvo-xc60": "XC60 -> Hyundai Tucson (crossover SUV)",
  "volvo-xc90-recharge": "XC90 -> Audi Q7 (SUV de gran tamaño)",
};

// Retorna la ruta GLB local de un vehículo (o "" si no hay mapping).
function modelo3dDeVehiculo(vehiculoId) {
  const stage = MODEL3D_MAP[vehiculoId];
  if (!stage) return "";
  return MODEL3D_STAGES[stage] || "";
}